server:
  port: 8080  #API服务访问端口
logging:
  level:
    com.qersoft.dao: debug
spring:
  datasource: # 通过spring定义数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动程序
    url: jdbc:mysql:// /school?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username:
    password:

    druid:
      one:
        max-active: 1000
        min-idle: 20
        max-wait: 2000





