
server:
  port: 8080
  servlet:
    context-path: /g12
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.97.36:3306/team12
    username: root
    password: 37132720041105Zh

    druid:
      one:
        max-active: 1000
        min-idle: 20
        max_wait: 2000